services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
      
  postgres-auction:
    image: postgres:15
    container_name: postgres-auction
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auction
    ports:
      - "5433:5432"
    volumes:
      - postgres-auction-data:/var/lib/postgresql/data
      
  postgres-bidding:
    image: postgres:15
    container_name: postgres-bidding
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: bidding
    ports:
      - "5434:5432"
    volumes:
      - postgres-bidding-data:/var/lib/postgresql/data
      
  postgres-analysis:
    image: postgres:15
    container_name: postgres-analysis
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: analysis
    ports:
      - "5435:5432"
    volumes:
      - postgres-analysis-data:/var/lib/postgresql/data
      
  nginx:
    image: nginx:1.29.1
    container_name: nginx
    depends_on:
      - api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/uploads
    
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0 -ui"
      
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -s --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  kibana:
    image: kibana:9.2.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:0.1
    container_name: api-gateway
    depends_on:
      - consul
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
    ports:
      - "8000:8000"
      
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    image: auth-service:0.1
    container_name: auth-service
    depends_on:
      - postgres-auth
      - consul
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth:5432/auth
      - SPRING_CLOUD_CONSUL_HOST=consul
    ports:
      - "8081:8081"
      
  auction-service:
    build:
      context: .
      dockerfile: auction-service/Dockerfile
    image: auction-service:0.1
    container_name: auction-service
    depends_on:
      kafka:
        condition: service_healthy
      postgres-auction:
        condition: service_started
      consul:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auction:5432/auction
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8082:8082"
    volumes:
      - ./images:/uploads
      
  bidding-service:
    build:
      context: .
      dockerfile: bidding-service/Dockerfile
    image: bidding-service:0.1
    container_name: bidding-service
    depends_on:
      kafka:
        condition: service_healthy
      postgres-bidding:
        condition: service_started
      consul:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-bidding:5432/bidding
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8083:8083"
      
  bid-request-service:
    build:
      context: .
      dockerfile: bid-request-service/Dockerfile
    image: bid-request-service:0.1
    container_name: bid-request-service
    depends_on:
      kafka:
        condition: service_healthy
      consul:
        condition: service_started
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8086:8086"
      
  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    image: notification-service:0.1
    container_name: notification-service
    depends_on:
      kafka:
        condition: service_healthy
      consul:
        condition: service_started
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8084:8084"
      
  analysis-service:
    build:
      context: .
      dockerfile: analysis-service/Dockerfile
    image: analysis-service:0.1
    container_name: analysis-service
    depends_on:
      postgres-analysis:
        condition: service_started
      kafka:
        condition: service_started
      consul:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-analysis:5432/analysis
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8085:8085"

  search-service:
    build:
      context: .
      dockerfile: search-service/Dockerfile
    image: search-service:0.1
    container_name: search-service
    depends_on:
      elasticsearch:
        condition: service_healthy
      kafka:
        condition: service_started
      consul:
        condition: service_started
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    ports:
      - "8087:8087"

volumes:
  postgres-auth-data: {}
  postgres-auction-data: {}
  postgres-bidding-data: {}
  postgres-analysis-data: {}
  esdata:
    driver: local

networks:
  default:
    driver: bridge